version: '3.1'
services:
    con-pool-nginx:
       image: nginx-mysql:v1.15
       restart: always
#       network_mode: host
       ports:
         - "3306:3306"
       privileged: true
       environment:
         - CONNECTION_LIMIT=65536
         - DESTINATION_IP=172.16.106.130
         - DESTINATION_PORT=3306
         - NGINXPORT=3306
         - KEEPLOVE_VALUE=1000
         - NGINX_WORKER=2
